const express = require("express");
const chatController = require("../controllers/chatController");
const router = express.Router();
const dotenv = require("dotenv");
dotenv.config();
const { Storage } = require("@google-cloud/storage");
const { json } = require("express/lib/response");
const checkAuth = require("../middlewares/checkAuth");
router.post("/createChat", checkAuth, chatController.createChat);
router.post("/sendMessage", checkAuth, chatController.sendMessage);
router.get("/getChat/:userId", checkAuth, chatController.getChat);
router.get("/getMessages/:chatId", checkAuth, chatController.getMessages);
module.exports = router;
